CREATE OR REPLACE TYPE OBJECT_SHIFT_PO_HOURS IS OBJECT (
  DEPT_ID NUMBER, 
  POS_HOURS_H NUMBER,
  POS_HOURS_M NUMBER
);
/
CREATE OR REPLACE TYPE TABLE_SHIFT_PO_HOURS IS TABLE OF OBJECT_SHIFT_PO_HOURS;
/
CREATE OR REPLACE
FUNCTION GET_SHIFT_PO_HOURS(FP_START_DTE IN VARCHAR2, FP_END_DTE IN VARCHAR2) 
RETURN TABLE_SHIFT_PO_HOURS PIPELINED IS
CURSOR CS_DEPT IS SELECT D.DEPT_ID FROM DEPARTMENT D;
CURSOR CS_SHIFT_PO_HOURS(CP_DEPT_ID IN NUMBER) IS
        SELECT SUM(SPLIT_NUMBER(MAX(TO_NUMBER(GET_HOURS(TO_CHAR(SP.TIME_FROM,'HH:MI AM'),TO_CHAR(SP.TIME_TO,'HH:MI AM'),'.'),'9999.99')),'H'))  POS_HOURS_H,
               SUM(SPLIT_NUMBER(MAX(TO_NUMBER(GET_HOURS(TO_CHAR(SP.TIME_FROM,'HH:MI AM'),TO_CHAR(SP.TIME_TO,'HH:MI AM'),'.'),'9999.99')),'M'))  POS_HOURS_M
                     FROM ALBERTA.SHIFT_POS SP,ALBERTA.DAILY_SHIFT_RECON DSR 
                     WHERE SP.DAILY_SHIFT_RECON_ID=DSR.DAILY_SHIFT_RECON_ID
                     AND SP.EMP_ID IN (SELECT E.EMP_ID FROM EMPLOYEE_SCHEDULE ES,EMPLOYEE E,DEPARTMENT D  
                     WHERE E.EMP_ID=ES.EMP_ID  AND ES.DTE BETWEEN TO_DATE(FP_START_DTE,'DD-MM-YYYY') 
                     AND TO_DATE(FP_END_DTE,'DD-MM-YYYY') AND ES.DEPT_ID=D.DEPT_ID  AND D.DEPT_ID=CP_DEPT_ID
                     GROUP BY E.EMP_ID)
                     AND DSR.RECON_DTE BETWEEN TO_DATE(FP_START_DTE,'DD-MM-YYYY') AND TO_DATE(FP_END_DTE,'DD-MM-YYYY') 
                     GROUP BY SP.EMP_ID,DSR.RECON_DTE,SP.SHIFT;
BEGIN
  FOR FL_D IN CS_DEPT LOOP
    FOR FL_POS IN CS_SHIFT_PO_HOURS(FL_D.DEPT_ID) LOOP
      PIPE ROW (OBJECT_SHIFT_PO_HOURS(FL_D.DEPT_ID, FL_POS.POS_HOURS_H, FL_POS.POS_HOURS_M));          
    END LOOP;
  END LOOP;    
  RETURN;  
END;
/