CREATE OR REPLACE TYPE OBJECT_SALES_PERFORMANCE_NEW IS OBJECT (
  COA_CDE VARCHAR2(32), 
  TITLE VARCHAR2(128),
  GROUP_NME VARCHAR2(32),
  T1 NUMBER, 
  T2 NUMBER, 
  T3 NUMBER, 
  T4 NUMBER, 
  T5 NUMBER, 
  W1 NUMBER, 
  W2 NUMBER, 
  W3 NUMBER, 
  W4 NUMBER, 
  W5 NUMBER
);
/
CREATE OR REPLACE TYPE TABLE_SALES_PERFORMANCE_NEW IS TABLE OF OBJECT_SALES_PERFORMANCE_NEW;
/
CREATE OR REPLACE
FUNCTION GET_SALES_PERFORMANCE_NEW(FP_MONTH IN VARCHAR2, FP_SITE_ID IN NUMBER, FP_FINYEAR_ID IN NUMBER, FP_COMPANY_ID IN NUMBER) 
RETURN TABLE_SALES_PERFORMANCE_NEW PIPELINED IS
CURSOR CS_SALES_PERFORMANCE_NEW IS 
        SELECT SP.REPORT_COLUMNS_MASTER_ID, MAX(RCM.COLUMN_NME) TITLE, MAX(RCM.GROUP_NME) GROUP_NME, SUM(SP.T1) T1, SUM(SP.T2) T2, SUM(SP.T3) T3, SUM(SP.T4) T4, SUM(SP.T5) T5, 
        SUM(CASE WHEN SP.COA_CDE IS NOT NULL THEN CASE WHEN SP.COA_CDE LIKE '375-02%' THEN SP.W1 ELSE ABS(SP.W1) END ELSE 0 END) W1, 
        SUM(CASE WHEN SP.COA_CDE IS NOT NULL THEN CASE WHEN SP.COA_CDE LIKE '375-02%' THEN SP.W2 ELSE ABS(SP.W2) END ELSE 0 END) W2, 
        SUM(CASE WHEN SP.COA_CDE IS NOT NULL THEN CASE WHEN SP.COA_CDE LIKE '375-02%' THEN SP.W3 ELSE ABS(SP.W3) END ELSE 0 END) W3, 
        SUM(CASE WHEN SP.COA_CDE IS NOT NULL THEN CASE WHEN SP.COA_CDE LIKE '375-02%' THEN SP.W4 ELSE ABS(SP.W4) END ELSE 0 END) W4, 
        SUM(CASE WHEN SP.COA_CDE IS NOT NULL THEN CASE WHEN SP.COA_CDE LIKE '375-02%' THEN SP.W5 ELSE ABS(SP.W5) END ELSE 0 END) W5 
        FROM (
             SELECT DST.REPORT_COLUMNS_MASTER_ID, NULL COA_CDE,
               SUM(CASE WHEN (MW.WEEK=1 AND (DST.DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DST.TARGET ELSE 0 END) T1,
               SUM(CASE WHEN (MW.WEEK=2 AND (DST.DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DST.TARGET ELSE 0 END) T2,
               SUM(CASE WHEN (MW.WEEK=3 AND (DST.DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DST.TARGET ELSE 0 END) T3,
               SUM(CASE WHEN (MW.WEEK=4 AND (DST.DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DST.TARGET ELSE 0 END) T4,
               SUM(CASE WHEN (MW.WEEK=5 AND (DST.DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DST.TARGET ELSE 0 END) T5,
               0 W1, 0 W2, 0 W3, 0 W4, 0 W5
              FROM DAILY_SALE_TARGET DST, MONTH_WEEKS MW WHERE DST.MONTH_NME=MW.MONTH_NME AND MW.WEEK_FOR='SP'
                AND DST.SITE_ID=FP_SITE_ID AND DST.COMPANY_ID=FP_COMPANY_ID AND DST.FIN_YEAR_ID=FP_FINYEAR_ID AND DST.MONTH_NME=FP_MONTH
              GROUP BY DST.REPORT_COLUMNS_MASTER_ID              
             UNION ALL
             SELECT VD.REPORT_COLUMNS_MASTER_ID, VD.COA_CDE, 0 T1, 0 T2, 0 T3, 0 T4, 0 T5,
               SUM(CASE WHEN (MW.WEEK=1 AND (VD.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  
                   CASE WHEN VD.COA_CDE LIKE '500-01-01%' THEN CASE WHEN VD.QTY<0 THEN VD.QTY ELSE 0 END ELSE VD.AMNT END ELSE 0 END) W1,
               SUM(CASE WHEN (MW.WEEK=2 AND (VD.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  
                   CASE WHEN VD.COA_CDE LIKE '500-01-01%' THEN CASE WHEN VD.QTY<0 THEN VD.QTY ELSE 0 END ELSE VD.AMNT END ELSE 0 END) W2,
               SUM(CASE WHEN (MW.WEEK=3 AND (VD.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  
                   CASE WHEN VD.COA_CDE LIKE '500-01-01%' THEN CASE WHEN VD.QTY<0 THEN VD.QTY ELSE 0 END ELSE VD.AMNT END ELSE 0 END) W3,
               SUM(CASE WHEN (MW.WEEK=4 AND (VD.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  
                   CASE WHEN VD.COA_CDE LIKE '500-01-01%' THEN CASE WHEN VD.QTY<0 THEN VD.QTY ELSE 0 END ELSE VD.AMNT END ELSE 0 END) W4,
               SUM(CASE WHEN (MW.WEEK=5 AND (VD.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  
                   CASE WHEN VD.COA_CDE LIKE '500-01-01%' THEN CASE WHEN VD.QTY<0 THEN VD.QTY ELSE 0 END ELSE VD.AMNT END ELSE 0 END) W5
             FROM ( SELECT RCD.REPORT_COLUMNS_MASTER_ID, VD.COA_CDE, VM.VOUCHER_DTE, VD.AMNT, NVL(VD.QTY,0) QTY, FP_MONTH MONTH_NME 
                    FROM VOUCHER_DETAIL VD, VOUCHER_MASTER VM, VOUCHER_SUB_TYPE VST, REPORT_COLUMNS_DETAIL RCD
                      WHERE VM.VOUCHER_MASTER_ID=VD.VOUCHER_MASTER_ID AND TO_CHAR(VM.VOUCHER_DTE,'MON-YYYY')=UPPER(FP_MONTH)
                      AND VM.VOUCHER_SUB_TYP_ID=VST.VOUCHER_SUB_TYP_ID AND VST.VOUCHER_SUB_TYP_DESC NOT IN ('FAL','FAG','CJV','AJV')
                      AND VM.CANCELLED_BY IS NULL AND VM.POSTED_IND='Y'
                      AND VM.SITE_ID=FP_SITE_ID AND VM.FIN_YEAR_ID=FP_FINYEAR_ID AND VM.COMPANY_ID=FP_COMPANY_ID  
                      AND VD.COA_CDE=RCD.COA_CDE AND RCD.REPORT_COLUMNS_MASTER_ID IN (SELECT RCM.REPORT_COLUMNS_MASTER_ID FROM REPORT_COLUMNS_MASTER RCM 
                          WHERE RCM.REPORT_TEMPLATE_ID=9 AND RCM.COMPANY_ID=FP_COMPANY_ID)
             ) VD, MONTH_WEEKS MW WHERE VD.MONTH_NME=MW.MONTH_NME AND MW.WEEK_FOR='SP' 
             GROUP BY VD.REPORT_COLUMNS_MASTER_ID, VD.COA_CDE
        ) SP, REPORT_COLUMNS_MASTER RCM WHERE SP.REPORT_COLUMNS_MASTER_ID=RCM.REPORT_COLUMNS_MASTER_ID 
          GROUP BY SP.REPORT_COLUMNS_MASTER_ID ORDER BY SP.REPORT_COLUMNS_MASTER_ID ASC;
BEGIN
    FOR FL_SP IN CS_SALES_PERFORMANCE_NEW LOOP
      PIPE ROW (OBJECT_SALES_PERFORMANCE_NEW(FL_SP.REPORT_COLUMNS_MASTER_ID, FL_SP.TITLE, FL_SP.GROUP_NME, FL_SP.T1, FL_SP.T2, FL_SP.T3, FL_SP.T4, FL_SP.T5, FL_SP.W1, FL_SP.W2, FL_SP.W3, FL_SP.W4, FL_SP.W5));          
    END LOOP;
  RETURN;  
END;
/




