CREATE OR REPLACE TYPE OBJECT_FUELCOST_FORPL IS OBJECT (
  MONTH_NBR NUMBER,
  COA_CDE VARCHAR2(32),  
  ITEM_COA_CDE VARCHAR2(32),    
  QTY NUMBER, 
  AMNT NUMBER,
  COST_VALUE NUMBER
);
/
CREATE OR REPLACE TYPE TABLE_FUELCOST_FORPL IS TABLE OF OBJECT_FUELCOST_FORPL;
/
CREATE OR REPLACE
FUNCTION GET_FUELCOST_FORPL(FP_FROM_DTE IN VARCHAR2, FP_END_DTE IN VARCHAR2, FP_SITE_ID IN NUMBER, FP_COMPANY_ID IN NUMBER) 
RETURN TABLE_FUELCOST_FORPL PIPELINED IS
CURSOR CS_DATA IS 
  SELECT BS.MONTH_NBR, BS.COA_CDE, BS.ITEM_COA_CDE, ABS(SUM(BS.QTY)) QTY, ABS(ABS(SUM(BS.AMNT))) AMNT, ABS(SUM(BS.COST_VALUE)) COST_VALUE  FROM (
     SELECT VST.VOUCHER_TYP, EXTRACT (MONTH FROM (VM.VOUCHER_DTE)) MONTH_NBR, VD.COA_CDE, VD.COA_CDE ITEM_COA_CDE, 
         NVL(VD.QTY,0) QTY, NVL(VD.AMNT,0) AMNT, ROUND((NVL(VD.QTY,0) * NVL(VD.BEFORE_COST_PRICE,0)),2) COST_VALUE
         FROM VOUCHER_DETAIL VD, VOUCHER_MASTER VM, VOUCHER_SUB_TYPE VST, SITE S
         WHERE VD.VOUCHER_MASTER_ID = VM.VOUCHER_MASTER_ID AND VM.VOUCHER_SUB_TYP_ID = VST.VOUCHER_SUB_TYP_ID
         AND VM.CANCELLED_BY IS NULL AND VM.POSTED_IND='Y' AND VM.SITE_ID=FP_SITE_ID 
         AND VM.SITE_ID=S.SITE_ID AND S.BUYSELL_START_DTE IS NOT NULL AND VM.VOUCHER_DTE >= S.BUYSELL_START_DTE
         AND VM.VOUCHER_DTE BETWEEN TO_DATE(FP_FROM_DTE,'DD-MM-YYYY') AND TO_DATE(FP_END_DTE,'DD-MM-YYYY')
         AND VD.COA_CDE IN (SELECT SBI.COA_CDE FROM SITE_BUY_ITEM SBI WHERE SBI.SITE_ID=FP_SITE_ID   AND SBI.COMPANY_ID=FP_COMPANY_ID )
         AND VM.COMPANY_ID=FP_COMPANY_ID AND VST.VOUCHER_TYP IN ('SI')
     UNION ALL
     SELECT 'ADD' VOUCHER_TYP, EXTRACT (MONTH FROM (R.VOUCHER_DTE)) MONTH_NBR, R.COA_CDE, R.ITEM_COA_CDE, ABS(SUM(R.ITEM_QTY)) QTY, ABS(SUM(R.ITEM_AMNT)) AMNT,
         ROUND(ABS(SUM(R.ITEM_VALUE)),2) COST_VALUE
         FROM TABLE(GET_FUEL_RECIPE(FP_FROM_DTE, FP_END_DTE, FP_SITE_ID, FP_COMPANY_ID)) R
         GROUP BY EXTRACT (MONTH FROM (R.VOUCHER_DTE)), R.COA_CDE, R.ITEM_COA_CDE 
  ) BS GROUP BY BS.MONTH_NBR, BS.COA_CDE, BS.ITEM_COA_CDE ORDER BY BS.MONTH_NBR, BS.COA_CDE, BS.ITEM_COA_CDE ;
BEGIN
    FOR FL_DATA IN CS_DATA LOOP
      PIPE ROW (OBJECT_FUELCOST_FORPL(FL_DATA.MONTH_NBR, FL_DATA.COA_CDE, FL_DATA.ITEM_COA_CDE, FL_DATA.QTY, FL_DATA.AMNT, FL_DATA.COST_VALUE));
    END LOOP;  
  RETURN;  
END;
/