CREATE OR REPLACE TYPE OBJECT_BANK_RECONCILIATION IS OBJECT (
  GRP_ORDER NUMBER,
  GRP_DESCRIPTION VARCHAR2(64),
  COA_CDE VARCHAR2(32),
  AMNT NUMBER 
);
/
CREATE OR REPLACE TYPE TABLE_BANK_RECONCILIATION IS TABLE OF OBJECT_BANK_RECONCILIATION;
/
CREATE OR REPLACE
FUNCTION GET_BANK_RECONCILIATION(FP_AS_ON_DATE IN VARCHAR2, FP_BU_ID IN NUMBER, FP_COMPANY_ID IN NUMBER) 
RETURN TABLE_BANK_RECONCILIATION PIPELINED IS
CURSOR CS_BR IS 
    SELECT BR.GRPORDER, BR.GRPDESCRIPTION, BR.COA_CDE, BR.CHQ_AMNT, TO_DATE(FP_AS_ON_DATE,'DD-MM-YYYY') AS_ON_DATE FROM ( 
        SELECT MAX(2) GRPORDER, MAX('ADD: CREDIT BY US NOT DEBITED BY BANK') GRPDESCRIPTION, VD.COA_CDE, -1*SUM(VD.AMNT) CHQ_AMNT
        FROM VOUCHER_DETAIL VD, VOUCHER_MASTER VM, VOUCHER_SUB_TYPE VST, BANK_ACCOUNT BA  
        WHERE VD.VOUCHER_MASTER_ID=VM.VOUCHER_MASTER_ID 
          AND VM.VOUCHER_SUB_TYP_ID=VST.VOUCHER_SUB_TYP_ID    
          AND VM.STATUS_IND IS NULL AND VM.CANCELLED_BY IS NULL AND VM.POSTED_IND='Y'
          AND VST.VOUCHER_TYP IN ('BPV','BTV') AND (VD.AMNT)<0 
          AND VD.COA_CDE=BA.COA_CDE AND VM.COMPANY_ID=FP_COMPANY_ID
          AND VM.VOUCHER_DTE<=TO_DATE(FP_AS_ON_DATE,'DD-MM-YYYY') 
          AND VM.SITE_ID IN (SELECT S.SITE_ID FROM SITE S, SITE_BUSINESS_UNIT SBU 
              WHERE S.SITE_ID=SBU.SITE_ID AND S.COMPANY_ID=SBU.COMPANY_ID 
              AND SBU.COMPANY_ID=FP_COMPANY_ID AND SBU.BUSINESS_UNIT_ID=FP_BU_ID)
          AND VM.VOUCHER_MASTER_ID NOT IN (SELECT VM_1.REF_VOUCHER_MASTER_ID FROM VOUCHER_MASTER VM_1 WHERE VM_1.REF_VOUCHER_MASTER_ID IS NOT NULL AND VM_1.COMPANY_ID=FP_COMPANY_ID) 
          AND (VD.CHQ_CLEARANCE_DTE IS NULL OR VD.CHQ_CLEARANCE_DTE > TO_DATE(FP_AS_ON_DATE,'DD-MM-YYYY')) 
        GROUP BY VD.COA_CDE
        UNION ALL 
        SELECT MAX(2) GrpOrder, MAX('ADD: CREDIT BY US NOT DEBITED BY BANK') GrpDescription, OBR.COA_CDE, -1*SUM(OBR.AMNT) CHQ_AMNT
        FROM OTHER_BANK_RECON OBR
        WHERE (OBR.AMNT)<0 AND OBR.STATUS_IND IS NULL
          AND OBR.COMPANY_ID=FP_COMPANY_ID  
          AND OBR.SITE_ID IN (SELECT S.SITE_ID FROM SITE S, SITE_BUSINESS_UNIT SBU 
              WHERE S.SITE_ID=SBU.SITE_ID AND S.COMPANY_ID=SBU.COMPANY_ID 
              AND SBU.COMPANY_ID=FP_COMPANY_ID AND SBU.BUSINESS_UNIT_ID=FP_BU_ID)           
          AND (OBR.CHQ_CLEARANCE_DTE IS NULL OR OBR.CHQ_CLEARANCE_DTE > TO_DATE(FP_AS_ON_DATE,'DD-MM-YYYY')) 
        GROUP BY OBR.COA_CDE  
        UNION ALL 
        SELECT MAX(2.5) GRPORDER, MAX('ADD: CREDIT BY US NOT DEBITED BY BANK (ON HOLD)') GRPDESCRIPTION, VD.COA_CDE, -1*SUM(VD.AMNT) CHQ_AMNT
        FROM VOUCHER_DETAIL VD, VOUCHER_MASTER VM, VOUCHER_SUB_TYPE VST, BANK_ACCOUNT BA 
        WHERE VD.VOUCHER_MASTER_ID=VM.VOUCHER_MASTER_ID 
          AND VM.VOUCHER_SUB_TYP_ID=VST.VOUCHER_SUB_TYP_ID
          AND VM.STATUS_IND='Y' AND VM.CANCELLED_BY IS NULL AND VM.POSTED_IND='Y'
          AND VST.VOUCHER_TYP IN ('BPV','BTV') AND (VD.AMNT)<0 
          AND VD.COA_CDE=BA.COA_CDE AND VM.COMPANY_ID=FP_COMPANY_ID
          AND VM.VOUCHER_DTE <= TO_DATE(FP_AS_ON_DATE,'DD-MM-YYYY')                     
          AND VM.SITE_ID IN (SELECT S.SITE_ID FROM SITE S, SITE_BUSINESS_UNIT SBU 
              WHERE S.SITE_ID=SBU.SITE_ID AND S.COMPANY_ID=SBU.COMPANY_ID 
              AND SBU.COMPANY_ID=FP_COMPANY_ID AND SBU.BUSINESS_UNIT_ID=FP_BU_ID)
          AND VM.VOUCHER_MASTER_ID NOT IN (SELECT VM_1.REF_VOUCHER_MASTER_ID FROM VOUCHER_MASTER VM_1 WHERE VM_1.REF_VOUCHER_MASTER_ID IS NOT NULL AND VM_1.COMPANY_ID=FP_COMPANY_ID) 
          AND (VD.CHQ_CLEARANCE_DTE IS NULL OR VD.CHQ_CLEARANCE_DTE > TO_DATE(FP_AS_ON_DATE,'DD-MM-YYYY')) 
        GROUP BY VD.COA_CDE    
        UNION ALL 
        SELECT MAX(2.5) GRPORDER, MAX('ADD: CREDIT BY US NOT DEBITED BY BANK (ON HOLD)') GRPDESCRIPTION, OBR.COA_CDE, -1*SUM(OBR.AMNT) CHQ_AMNT
        FROM OTHER_BANK_RECON OBR
        WHERE (OBR.AMNT)<0 AND OBR.STATUS_IND='Y'
          AND OBR.COMPANY_ID=FP_COMPANY_ID  
          AND OBR.SITE_ID IN (SELECT S.SITE_ID FROM SITE S, SITE_BUSINESS_UNIT SBU 
              WHERE S.SITE_ID=SBU.SITE_ID AND S.COMPANY_ID=SBU.COMPANY_ID 
              AND SBU.COMPANY_ID=FP_COMPANY_ID AND SBU.BUSINESS_UNIT_ID=FP_BU_ID) 
          AND (OBR.CHQ_CLEARANCE_DTE IS NULL OR OBR.CHQ_CLEARANCE_DTE > TO_DATE(FP_AS_ON_DATE,'DD-MM-YYYY')) 
        GROUP BY OBR.COA_CDE  
        UNION ALL 
        SELECT MAX(2.8) GRPORDER, MAX('ADD: CREDIT BY US NOT DEBITED BY BANK (SUBSEQUENTLY REVERSED)') GRPDESCRIPTION, VD.COA_CDE, -1*SUM(VD.AMNT) CHQ_AMNT
        FROM VOUCHER_DETAIL VD, VOUCHER_MASTER VM, VOUCHER_SUB_TYPE VST, BANK_ACCOUNT BA 
        WHERE VD.VOUCHER_MASTER_ID=VM.VOUCHER_MASTER_ID 
          AND VM.VOUCHER_SUB_TYP_ID=VST.VOUCHER_SUB_TYP_ID 
          AND VM.CANCELLED_BY IS NULL AND VM.POSTED_IND='Y'
          AND VST.VOUCHER_TYP IN ('BPV','BTV') AND (VD.AMNT)<0 
          AND VD.COA_CDE=BA.COA_CDE AND VM.COMPANY_ID=FP_COMPANY_ID
          AND VM.VOUCHER_DTE <= TO_DATE(FP_AS_ON_DATE,'DD-MM-YYYY')            
          AND VM.SITE_ID IN (SELECT S.SITE_ID FROM SITE S, SITE_BUSINESS_UNIT SBU 
              WHERE S.SITE_ID=SBU.SITE_ID AND S.COMPANY_ID=SBU.COMPANY_ID 
              AND SBU.COMPANY_ID=FP_COMPANY_ID AND SBU.BUSINESS_UNIT_ID=FP_BU_ID)
          AND VM.VOUCHER_MASTER_ID IN (SELECT VM_1.REF_VOUCHER_MASTER_ID FROM VOUCHER_MASTER VM_1 WHERE VM_1.REF_VOUCHER_MASTER_ID IS NOT NULL AND VM_1.VOUCHER_DTE > TO_DATE(FP_AS_ON_DATE,'DD-MM-YYYY') AND VM_1.COMPANY_ID=FP_COMPANY_ID)    
          --AND (SELECT VM_1.VOUCHER_DTE FROM VOUCHER_MASTER VM_1 WHERE VM_1.REF_VOUCHER_MASTER_ID=VM.VOUCHER_MASTER_ID AND VM_1.VOUCHER_DTE > TO_DATE(FP_AS_ON_DATE,'DD-MM-YYYY')) IS NOT NULL 
          AND (VD.CHQ_CLEARANCE_DTE IS NULL OR VD.CHQ_CLEARANCE_DTE > TO_DATE(FP_AS_ON_DATE,'DD-MM-YYYY')) 
        GROUP BY VD.COA_CDE  
        UNION ALL 
        SELECT MAX(3) GRPORDER, MAX('LESS: DEBITED BY US NOT CREDIT BY BANK') GRPDESCRIPTION, VD.COA_CDE, -1*SUM(VD.AMNT) CHQ_AMNT
        FROM VOUCHER_DETAIL VD, VOUCHER_MASTER VM, BANK_ACCOUNT BA, VOUCHER_SUB_TYPE VST 
        WHERE VD.VOUCHER_MASTER_ID=VM.VOUCHER_MASTER_ID 
          AND VM.VOUCHER_SUB_TYP_ID=VST.VOUCHER_SUB_TYP_ID    
          AND VM.STATUS_IND IS NULL AND VM.CANCELLED_BY IS NULL AND VM.POSTED_IND='Y'
          AND VST.VOUCHER_TYP IN ('BRV','BTV') AND (VD.AMNT)>0
          AND VD.COA_CDE=BA.COA_CDE AND VM.COMPANY_ID=FP_COMPANY_ID
          AND VM.VOUCHER_DTE <= TO_DATE(FP_AS_ON_DATE,'DD-MM-YYYY')  
          AND VM.SITE_ID IN (SELECT S.SITE_ID FROM SITE S, SITE_BUSINESS_UNIT SBU 
              WHERE S.SITE_ID=SBU.SITE_ID AND S.COMPANY_ID=SBU.COMPANY_ID 
              AND SBU.COMPANY_ID=FP_COMPANY_ID AND SBU.BUSINESS_UNIT_ID=FP_BU_ID)
          AND VM.VOUCHER_MASTER_ID NOT IN (SELECT VM_1.REF_VOUCHER_MASTER_ID FROM VOUCHER_MASTER VM_1 WHERE VM_1.REF_VOUCHER_MASTER_ID IS NOT NULL AND VM_1.COMPANY_ID=FP_COMPANY_ID) 
          AND (VD.CHQ_CLEARANCE_DTE IS NULL OR VD.CHQ_CLEARANCE_DTE > TO_DATE(FP_AS_ON_DATE,'DD-MM-YYYY')) 
        GROUP BY VD.COA_CDE  
        UNION ALL 
        SELECT MAX(3) GrpOrder, MAX('LESS: DEBITED BY US NOT CREDIT BY BANK') GrpDescription, OBR.COA_CDE, -1*SUM(OBR.AMNT) CHQ_AMNT
        FROM OTHER_BANK_RECON OBR
        WHERE (OBR.AMNT)>0 AND OBR.COMPANY_ID=FP_COMPANY_ID
          AND OBR.SITE_ID IN (SELECT S.SITE_ID FROM SITE S, SITE_BUSINESS_UNIT SBU 
              WHERE S.SITE_ID=SBU.SITE_ID AND S.COMPANY_ID=SBU.COMPANY_ID 
              AND SBU.COMPANY_ID=FP_COMPANY_ID AND SBU.BUSINESS_UNIT_ID=FP_BU_ID)
          AND (OBR.CHQ_CLEARANCE_DTE IS NULL OR OBR.CHQ_CLEARANCE_DTE > TO_DATE(FP_AS_ON_DATE,'DD-MM-YYYY')) 
        GROUP BY OBR.COA_CDE  
        UNION ALL 
        SELECT MAX(3.8) GrpOrder, MAX('LESS: DEBITED BY US NOT CREDIT BY BANK (SUBSEQUENTLY REVERSED)') GrpDescription, VD.COA_CDE, -1*SUM(VD.AMNT) CHQ_AMNT
        FROM VOUCHER_DETAIL VD, VOUCHER_MASTER VM, BANK_ACCOUNT BA, VOUCHER_SUB_TYPE VST 
        WHERE VD.VOUCHER_MASTER_ID=VM.VOUCHER_MASTER_ID           
          AND VM.VOUCHER_SUB_TYP_ID=VST.VOUCHER_SUB_TYP_ID
          AND VM.CANCELLED_BY IS NULL AND VM.POSTED_IND='Y'
          AND VST.VOUCHER_TYP IN ('BRV','BTV') AND (VD.AMNT)>0 
          AND VD.COA_CDE=BA.COA_CDE AND VM.COMPANY_ID=FP_COMPANY_ID
          AND VM.VOUCHER_DTE <= TO_DATE(FP_AS_ON_DATE,'DD-MM-YYYY') 
          AND VM.SITE_ID IN (SELECT S.SITE_ID FROM SITE S, SITE_BUSINESS_UNIT SBU 
              WHERE S.SITE_ID=SBU.SITE_ID AND S.COMPANY_ID=SBU.COMPANY_ID 
              AND SBU.COMPANY_ID=FP_COMPANY_ID AND SBU.BUSINESS_UNIT_ID=FP_BU_ID)
          AND VM.VOUCHER_MASTER_ID IN (SELECT VM_1.REF_VOUCHER_MASTER_ID FROM VOUCHER_MASTER VM_1 WHERE VM_1.REF_VOUCHER_MASTER_ID IS NOT NULL AND VM_1.VOUCHER_DTE > TO_DATE(FP_AS_ON_DATE,'DD-MM-YYYY') AND VM_1.COMPANY_ID=FP_COMPANY_ID)    
          --AND (SELECT VM_1.VOUCHER_DTE FROM VOUCHER_MASTER VM_1 WHERE VM_1.REF_VOUCHER_MASTER_ID=VM.VOUCHER_MASTER_ID AND VM_1.VOUCHER_DTE > TO_DATE(FP_AS_ON_DATE,'DD-MM-YYYY')) IS NOT NULL 
          AND (VD.CHQ_CLEARANCE_DTE IS NULL OR VD.CHQ_CLEARANCE_DTE > TO_DATE(FP_AS_ON_DATE,'DD-MM-YYYY')) 
        GROUP BY VD.COA_CDE  
        UNION ALL 
        SELECT MAX(1) GRPORDER, MAX('BALANCE: AS PER LEDGER') GRPDESCRIPTION, VD.COA_CDE, SUM(VD.AMNT) LEDGER_BAL                    
        FROM VOUCHER_DETAIL VD, VOUCHER_MASTER VM, BANK_ACCOUNT BA 
        WHERE VD.VOUCHER_MASTER_ID=VM.VOUCHER_MASTER_ID
          AND VM.CANCELLED_BY IS NULL AND VM.POSTED_IND='Y'
          AND VD.COA_CDE=BA.COA_CDE AND VM.COMPANY_ID=FP_COMPANY_ID
          AND VM.VOUCHER_DTE <= TO_DATE(FP_AS_ON_DATE,'DD-MM-YYYY')          
          AND VM.SITE_ID IN (SELECT S.SITE_ID FROM SITE S, SITE_BUSINESS_UNIT SBU 
              WHERE S.SITE_ID=SBU.SITE_ID AND S.COMPANY_ID=SBU.COMPANY_ID 
              AND SBU.COMPANY_ID=FP_COMPANY_ID AND SBU.BUSINESS_UNIT_ID=FP_BU_ID)
        GROUP BY VD.COA_CDE 
        UNION ALL 
        SELECT MAX(4) GRPORDER, MAX('BANK BALANCE') GRPDESCRIPTION, BB.COA_CDE, SUM(BB.AMNT) LEDGER_BAL                    
        FROM BANK_BALANCE BB
        WHERE BB.COMPANY_ID=FP_COMPANY_ID  
          AND BB.BAL_DTE = TO_DATE(FP_AS_ON_DATE,'DD-MM-YYYY') 
          AND BB.SITE_ID IN (SELECT S.SITE_ID FROM SITE S, SITE_BUSINESS_UNIT SBU 
              WHERE S.SITE_ID=SBU.SITE_ID AND S.COMPANY_ID=SBU.COMPANY_ID 
              AND SBU.COMPANY_ID=FP_COMPANY_ID AND SBU.BUSINESS_UNIT_ID=FP_BU_ID)
        GROUP BY BB.COA_CDE   
    ) BR ORDER BY BR.COA_CDE ASC, BR.GRPORDER ASC;
    
BEGIN
  FOR FL_BR IN CS_BR LOOP
    IF (FL_BR.CHQ_AMNT = 0) THEN  
      IF (FL_BR.GRPORDER <> 1) THEN 
        PIPE ROW (OBJECT_BANK_RECONCILIATION(FL_BR.GRPORDER, FL_BR.GRPDESCRIPTION, FL_BR.COA_CDE, FL_BR.CHQ_AMNT));
      END IF;
    ELSE 
      PIPE ROW (OBJECT_BANK_RECONCILIATION(FL_BR.GRPORDER, FL_BR.GRPDESCRIPTION, FL_BR.COA_CDE, FL_BR.CHQ_AMNT));
    END IF;  
  END LOOP;
  RETURN;  
END;
/  