CREATE OR REPLACE TYPE OBJECT_SALES_PERFORMANCE IS OBJECT (
  COA_CDE VARCHAR2(32), 
  TITLE VARCHAR2(128),
  TARGET NUMBER, 
  W1 NUMBER, 
  W2 NUMBER, 
  W3 NUMBER, 
  W4 NUMBER, 
  W5 NUMBER
);
/
CREATE OR REPLACE TYPE TABLE_SALES_PERFORMANCE IS TABLE OF OBJECT_SALES_PERFORMANCE;
/
CREATE OR REPLACE
FUNCTION GET_SALES_PERFORMANCE(FP_MONTH IN VARCHAR2, FP_SITE_ID IN NUMBER, FP_FINYEAR_ID IN NUMBER, FP_COMPANY_ID IN NUMBER) 
RETURN TABLE_SALES_PERFORMANCE PIPELINED IS
CURSOR CS_SALES_PERFORMANCE IS 
        SELECT SP.COA_CDE, MAX(COA.TITLE) TITLE, SUM(SP.TARGET) TARGET, 
        SUM(CASE WHEN SP.COA_CDE LIKE '375-02%' THEN SP.W1 ELSE ABS(SP.W1) END) W1, 
        SUM(CASE WHEN SP.COA_CDE LIKE '375-02%' THEN SP.W2 ELSE ABS(SP.W2) END) W2, 
        SUM(CASE WHEN SP.COA_CDE LIKE '375-02%' THEN SP.W3 ELSE ABS(SP.W3) END) W3, 
        SUM(CASE WHEN SP.COA_CDE LIKE '375-02%' THEN SP.W4 ELSE ABS(SP.W4) END) W4, 
        SUM(CASE WHEN SP.COA_CDE LIKE '375-02%' THEN SP.W5 ELSE ABS(SP.W5) END) W5 
        FROM (
             SELECT COA.COA_CDE, NVL(ST.TARGET,0) TARGET, 0 W1, 0 W2, 0 W3, 0 W4, 0 W5 FROM (
                  SELECT ST.COA_CDE, ST.TARGET FROM SALES_TARGET ST
                  WHERE ST.SITE_ID=FP_SITE_ID  AND ST.COMPANY_ID=FP_COMPANY_ID  AND ST.FIN_YEAR_ID=FP_FINYEAR_ID  AND ST.MONTH_NME=FP_MONTH
             ) ST, CHART_OF_ACCOUNT COA 
             WHERE COA.COA_CDE=ST.COA_CDE(+) AND COA.COMPANY_ID=FP_COMPANY_ID 
             AND COA.COA_CDE IN (SELECT COA.COA_CDE FROM CHART_OF_ACCOUNT COA WHERE COA.ENTRY_LEVEL_IND='Y'
                                   START WITH COA.COA_CDE IN (SELECT CAD.COA_CDE FROM COA_ASSOCIATION_DETAIL CAD, COA_ASSOCIATION CA
                                   WHERE CAD.COA_ASSOCIATION_ID=CA.COA_ASSOCIATION_ID AND CA.ASSOCIATION_TITLE IN ('SALES TARGET'))
                                   CONNECT BY PRIOR COA.COA_CDE=COA.PARENT_CDE UNION ALL
                                 SELECT COA.COA_CDE FROM (SELECT COA.COA_CDE FROM CHART_OF_ACCOUNT COA  WHERE COA.ENTRY_LEVEL_IND='Y' 
                                   START WITH COA.COA_CDE IN (SELECT CAD.COA_CDE FROM COA_ASSOCIATION_DETAIL CAD, COA_ASSOCIATION CA 
                                   WHERE CAD.COA_ASSOCIATION_ID=CA.COA_ASSOCIATION_ID AND CA.ASSOCIATION_TITLE IN ('DAILY SHEET ITEMS')) 
                                   CONNECT BY PRIOR COA.COA_CDE=COA.PARENT_CDE
                                 ) COA, SITE_INVENTORY SI WHERE COA.COA_CDE=SI.COA_CDE AND SI.SITE_ID=FP_SITE_ID) 
             UNION ALL
             SELECT DDS.COA_CDE, MIN(0) TARGET,
               SUM(CASE WHEN (MW.WEEK=1 AND (DDS.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DDS.SAL_QTY ELSE 0 END) W1,
               SUM(CASE WHEN (MW.WEEK=2 AND (DDS.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DDS.SAL_QTY ELSE 0 END) W2,
               SUM(CASE WHEN (MW.WEEK=3 AND (DDS.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DDS.SAL_QTY ELSE 0 END) W3,
               SUM(CASE WHEN (MW.WEEK=4 AND (DDS.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DDS.SAL_QTY ELSE 0 END) W4,
               SUM(CASE WHEN (MW.WEEK=5 AND (DDS.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DDS.SAL_QTY ELSE 0 END) W5
              FROM ( SELECT DDS.COA_CDE, DDS.VOUCHER_DTE, NVL(DDS.SAL_QTY,0) SAL_QTY, DDS.MONTH_NME FROM DEPT_DAILY_SALE DDS
                      WHERE DDS.MONTH_NME=FP_MONTH AND DDS.SITE_ID=FP_SITE_ID  AND DDS.FIN_YEAR_ID=FP_FINYEAR_ID AND DDS.COMPANY_ID=FP_COMPANY_ID
              ) DDS, MONTH_WEEKS MW WHERE DDS.MONTH_NME=MW.MONTH_NME AND MW.WEEK_FOR='SP' GROUP BY DDS.COA_CDE
             UNION ALL
             SELECT ('500-01-06-0020') COA_CDE, 0 TARGET,
              (CASE WHEN SW.W1_TOT_TRAN<>0 THEN ROUND(((SW.W1_PP_TRAN/SW.W1_TOT_TRAN)*100),2) ELSE 0 END) W1,
              (CASE WHEN SW.W2_TOT_TRAN<>0 THEN ROUND(((SW.W2_PP_TRAN/SW.W2_TOT_TRAN)*100),2) ELSE 0 END) W2,
              (CASE WHEN SW.W3_TOT_TRAN<>0 THEN ROUND(((SW.W3_PP_TRAN/SW.W3_TOT_TRAN)*100),2) ELSE 0 END) W3,
              (CASE WHEN SW.W4_TOT_TRAN<>0 THEN ROUND(((SW.W4_PP_TRAN/SW.W4_TOT_TRAN)*100),2) ELSE 0 END) W4,
              (CASE WHEN SW.W5_TOT_TRAN<>0 THEN ROUND(((SW.W5_PP_TRAN/SW.W5_TOT_TRAN)*100),2) ELSE 0 END) W5
              FROM (
                SELECT SUM(CASE WHEN (MW.WEEK=1 AND (DSR.RECON_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DSR.TOT_TRANSACTION ELSE 0 END) W1_TOT_TRAN,
                  SUM(CASE WHEN (MW.WEEK=1 AND (DSR.RECON_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DSR.PP_TRANSACTION ELSE 0 END) W1_PP_TRAN,
                  SUM(CASE WHEN (MW.WEEK=2 AND (DSR.RECON_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DSR.TOT_TRANSACTION ELSE 0 END) W2_TOT_TRAN,
                  SUM(CASE WHEN (MW.WEEK=2 AND (DSR.RECON_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DSR.PP_TRANSACTION ELSE 0 END) W2_PP_TRAN,
                  SUM(CASE WHEN (MW.WEEK=3 AND (DSR.RECON_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DSR.TOT_TRANSACTION ELSE 0 END) W3_TOT_TRAN,
                  SUM(CASE WHEN (MW.WEEK=3 AND (DSR.RECON_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DSR.PP_TRANSACTION ELSE 0 END) W3_PP_TRAN,
                  SUM(CASE WHEN (MW.WEEK=4 AND (DSR.RECON_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DSR.TOT_TRANSACTION ELSE 0 END) W4_TOT_TRAN,
                  SUM(CASE WHEN (MW.WEEK=4 AND (DSR.RECON_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DSR.PP_TRANSACTION ELSE 0 END) W4_PP_TRAN,
                  SUM(CASE WHEN (MW.WEEK=5 AND (DSR.RECON_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DSR.TOT_TRANSACTION ELSE 0 END) W5_TOT_TRAN,
                  SUM(CASE WHEN (MW.WEEK=5 AND (DSR.RECON_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DSR.PP_TRANSACTION ELSE 0 END) W5_PP_TRAN
                  FROM (
                    SELECT DSR.RECON_DTE, MAX(FP_MONTH) MONTH_NME, SUM(NVL(SP.TOTAL_TRANSACTION,0)+NVL(SP.FUEL_TRANSACTION,0)) TOT_TRANSACTION, 
                    MAX(NVL(SP.PP_TRANSACTION,0)) PP_TRANSACTION FROM SHIFT_POS SP,DAILY_SHIFT_RECON DSR
                    WHERE SP.DAILY_SHIFT_RECON_ID=DSR.DAILY_SHIFT_RECON_ID AND DSR.COMPANY_ID=FP_COMPANY_ID
                      AND DSR.SITE_ID=FP_SITE_ID AND TO_CHAR(DSR.RECON_DTE,'MON-YYYY')=UPPER(FP_MONTH)
                    GROUP BY DSR.RECON_DTE
                  ) DSR, MONTH_WEEKS MW 
                   WHERE DSR.MONTH_NME=MW.MONTH_NME AND MW.WEEK_FOR='SP'
               ) SW
             UNION ALL
             SELECT VD.COA_CDE, MIN(0) TARGET,
               SUM(CASE WHEN (MW.WEEK=1 AND (VD.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  
                   CASE WHEN VD.COA_CDE LIKE '500-01-01%' THEN CASE WHEN VD.QTY<0 THEN VD.QTY ELSE 0 END ELSE VD.AMNT END ELSE 0 END) W1,
               SUM(CASE WHEN (MW.WEEK=2 AND (VD.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  
                   CASE WHEN VD.COA_CDE LIKE '500-01-01%' THEN CASE WHEN VD.QTY<0 THEN VD.QTY ELSE 0 END ELSE VD.AMNT END ELSE 0 END) W2,
               SUM(CASE WHEN (MW.WEEK=3 AND (VD.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  
                   CASE WHEN VD.COA_CDE LIKE '500-01-01%' THEN CASE WHEN VD.QTY<0 THEN VD.QTY ELSE 0 END ELSE VD.AMNT END ELSE 0 END) W3,
               SUM(CASE WHEN (MW.WEEK=4 AND (VD.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  
                   CASE WHEN VD.COA_CDE LIKE '500-01-01%' THEN CASE WHEN VD.QTY<0 THEN VD.QTY ELSE 0 END ELSE VD.AMNT END ELSE 0 END) W4,
               SUM(CASE WHEN (MW.WEEK=5 AND (VD.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  
                   CASE WHEN VD.COA_CDE LIKE '500-01-01%' THEN CASE WHEN VD.QTY<0 THEN VD.QTY ELSE 0 END ELSE VD.AMNT END ELSE 0 END) W5
             FROM ( SELECT VD.COA_CDE, VM.VOUCHER_DTE, VD.AMNT, NVL(VD.QTY,0) QTY, FP_MONTH MONTH_NME FROM VOUCHER_DETAIL VD, VOUCHER_MASTER VM, VOUCHER_SUB_TYPE VST
                      WHERE VM.VOUCHER_MASTER_ID=VD.VOUCHER_MASTER_ID AND TO_CHAR(VM.VOUCHER_DTE,'MON-YYYY')=UPPER(FP_MONTH)
                      AND VM.VOUCHER_SUB_TYP_ID=VST.VOUCHER_SUB_TYP_ID AND VST.VOUCHER_SUB_TYP_DESC NOT IN ('FAL','FAG','CJV','AJV')
                      AND VM.SITE_ID=FP_SITE_ID  AND VM.FIN_YEAR_ID=FP_FINYEAR_ID  AND VM.COMPANY_ID=FP_COMPANY_ID  AND VM.CANCELLED_BY IS NULL AND VM.POSTED_IND='Y'
                      AND VD.COA_CDE IN (SELECT COA.COA_CDE FROM CHART_OF_ACCOUNT COA WHERE COA.ENTRY_LEVEL_IND='Y'
                                          START WITH COA.COA_CDE IN (SELECT CAD.COA_CDE FROM COA_ASSOCIATION_DETAIL CAD, COA_ASSOCIATION CA
                                          WHERE CAD.COA_ASSOCIATION_ID=CA.COA_ASSOCIATION_ID AND CA.ASSOCIATION_TITLE IN ('SALES TARGET'))
                                          CONNECT BY PRIOR COA.COA_CDE=COA.PARENT_CDE UNION ALL
                                         SELECT COA.COA_CDE FROM (SELECT COA.COA_CDE FROM CHART_OF_ACCOUNT COA  WHERE COA.ENTRY_LEVEL_IND='Y' 
                                           START WITH COA.COA_CDE IN (SELECT CAD.COA_CDE FROM COA_ASSOCIATION_DETAIL CAD, COA_ASSOCIATION CA 
                                           WHERE CAD.COA_ASSOCIATION_ID=CA.COA_ASSOCIATION_ID AND CA.ASSOCIATION_TITLE IN ('DAILY SHEET ITEMS')) 
                                           CONNECT BY PRIOR COA.COA_CDE=COA.PARENT_CDE
                                         ) COA, SITE_INVENTORY SI WHERE COA.COA_CDE=SI.COA_CDE AND SI.SITE_ID=FP_SITE_ID)
             ) VD, MONTH_WEEKS MW WHERE VD.MONTH_NME=MW.MONTH_NME AND MW.WEEK_FOR='SP' GROUP BY VD.COA_CDE
        ) SP, CHART_OF_ACCOUNT COA WHERE SP.COA_CDE=COA.COA_CDE GROUP BY SP.COA_CDE ORDER BY SP.COA_CDE ASC;
BEGIN
    FOR FL_SP IN CS_SALES_PERFORMANCE LOOP
      PIPE ROW (OBJECT_SALES_PERFORMANCE(FL_SP.COA_CDE, FL_SP.TITLE, FL_SP.TARGET, FL_SP.W1, FL_SP.W2, FL_SP.W3, FL_SP.W4, FL_SP.W5));          
    END LOOP;
  RETURN;  
END;
/




