CREATE OR REPLACE TYPE OBJECT_PL_MONTH IS OBJECT (
  SITE_ID NUMBER,
  MONTH_NBR NUMBER,
  SEQ_NBR NUMBER,
  TITLE VARCHAR2(128),
  DISPLAY_TXT VARCHAR2(128),
  SUB_TITLE VARCHAR2(128),   
  COA_CDE VARCHAR2(32), 
  COA_TITLE VARCHAR2(128), 
  AMNT NUMBER
);
/
CREATE OR REPLACE TYPE TABLE_PL_MONTH IS TABLE OF OBJECT_PL_MONTH;
/
CREATE OR REPLACE
FUNCTION GET_PL_MONTH(FP_MANAGEMENT_ACCOUNTS_ID IN NUMBER, FP_FROM_DTE IN VARCHAR2, FP_END_DTE IN VARCHAR2, FP_BU_ID IN NUMBER, FP_SITE_ID IN NUMBER, FP_FINYEAR_ID IN NUMBER, FP_COMPANY_ID IN NUMBER) 
RETURN TABLE_PL_MONTH PIPELINED IS
CURSOR CS_PL_MONTH IS 
  SELECT MA.*, COA.TITLE COA_TITLE FROM TABLE(GET_MANAGEMENT_ACCOUNTS(FP_MANAGEMENT_ACCOUNTS_ID, FP_FROM_DTE,FP_END_DTE,FP_SITE_ID,FP_FINYEAR_ID,FP_COMPANY_ID,'Y')) MA, CHART_OF_ACCOUNT COA 
    WHERE MA.COA_CDE=COA.COA_CDE(+);

BEGIN
  FOR FL_PL IN CS_PL_MONTH LOOP   
    IF (FL_PL.TITLE='SALES' OR FL_PL.TITLE='OTHER INCOME') THEN
      PIPE ROW (OBJECT_PL_MONTH(FP_SITE_ID, FL_PL.MONTH_NBR, FL_PL.SEQ_NBR, FL_PL.TITLE, FL_PL.DISPLAY_TXT, FL_PL.SUB_TITLE, FL_PL.COA_CDE, FL_PL.COA_TITLE, -1*(FL_PL.AMNT)));     
    ELSE  
      PIPE ROW (OBJECT_PL_MONTH(FP_SITE_ID, FL_PL.MONTH_NBR, FL_PL.SEQ_NBR, FL_PL.TITLE, FL_PL.DISPLAY_TXT, FL_PL.SUB_TITLE, FL_PL.COA_CDE, FL_PL.COA_TITLE, FL_PL.AMNT));      
    END IF;      
  END LOOP;
END;
/