CREATE OR REPLACE TYPE OBJECT_QSR_SALES_PERFORMANCE_W IS OBJECT (
  COA_CDE VARCHAR2(32), 
  TITLE VARCHAR2(128),
  TARGET NUMBER, 
  SOLD NUMBER,
  SOLD_DTE DATE  
);
/
CREATE OR REPLACE TYPE TABLE_QSR_SALES_PERFORMANCE_W IS TABLE OF OBJECT_QSR_SALES_PERFORMANCE_W;
/
CREATE OR REPLACE
FUNCTION GET_QSR_SALES_PERFORMANCE_W(FP_MONTH IN VARCHAR2, FP_START_DTE IN VARCHAR2, FP_END_DTE IN VARCHAR2, FP_WEEK IN VARCHAR2, FP_SITE_ID IN NUMBER, FP_FINYEAR_ID IN NUMBER, FP_COMPANY_ID IN NUMBER) 
RETURN TABLE_QSR_SALES_PERFORMANCE_W PIPELINED IS
CURSOR CS_QSR_SALES_PERFORMANCE_W IS 
        SELECT SP.COA_CDE, MAX(COA.TITLE) TITLE, ABS(SUM(SP.TARGET)) TARGET, ABS(SUM(SP.SOLD)) SOLD, SP.SOLD_DTE  FROM (
             SELECT ST.COA_CDE, NVL(ST.TARGET,0) TARGET, 0 SOLD, NULL SOLD_DTE FROM (
                  SELECT QTD.COA_CDE, SUM(CASE WHEN QTD.WEEK=FP_WEEK THEN NVL(QTD.TARGET,0) ELSE 0 END) TARGET, 0 SOLD, NULL SOLD_DTE
                  FROM QSR_TARGET_MASTER QTM,QSR_TARGET_DETAIL QTD
                   WHERE QTM.QSR_TARGET_MASTER_ID=QTD.QSR_TARGET_MASTER_ID
                   AND QTM.FIN_YEAR_ID=FP_FINYEAR_ID AND QTM.SITE_ID=FP_SITE_ID
                   AND QTM.MONTH_NME=FP_MONTH AND QTM.COMPANY_ID=FP_COMPANY_ID
                  GROUP BY QTD.COA_CDE                  
             ) ST WHERE ST.COA_CDE IN (SELECT COA.COA_CDE FROM CHART_OF_ACCOUNT COA WHERE COA.ENTRY_LEVEL_IND='Y'
                                   START WITH COA.COA_CDE IN (SELECT CAD.COA_CDE FROM COA_ASSOCIATION_DETAIL CAD, COA_ASSOCIATION CA
                                   WHERE CAD.COA_ASSOCIATION_ID=CA.COA_ASSOCIATION_ID AND CA.ASSOCIATION_TITLE IN ('QSR SALES TARGET', 'QSR SALES ACTUAL'))
                                   CONNECT BY PRIOR COA.COA_CDE=COA.PARENT_CDE) 
             UNION ALL
             SELECT DDS.COA_CDE, 0 TARGET, SUM(DDS.SAL_QTY) SOLD, DDS.VOUCHER_DTE SOLD_DTE
              FROM ( SELECT DDS.COA_CDE, DDS.VOUCHER_DTE, NVL(DDS.SAL_QTY,0) SAL_QTY, DDS.MONTH_NME 
                      FROM DEPT_DAILY_SALE DDS, SITE_INVENTORY SI
                      WHERE (DDS.VOUCHER_DTE BETWEEN TO_DATE(FP_START_DTE,'DD-MM-YYYY') AND TO_DATE(FP_END_DTE,'DD-MM-YYYY'))  
                      AND DDS.SITE_ID=FP_SITE_ID AND DDS.FIN_YEAR_ID=FP_FINYEAR_ID AND DDS.COMPANY_ID=FP_COMPANY_ID
                      AND DDS.COA_CDE=SI.COA_CDE AND SI.SITE_ID=FP_SITE_ID
                      AND DDS.COA_CDE IN (SELECT COA.COA_CDE FROM CHART_OF_ACCOUNT COA WHERE COA.ENTRY_LEVEL_IND='Y'
                                            START WITH COA.COA_CDE IN (SELECT CAD.COA_CDE FROM COA_ASSOCIATION_DETAIL CAD, COA_ASSOCIATION CA
                                              WHERE CAD.COA_ASSOCIATION_ID=CA.COA_ASSOCIATION_ID AND CA.ASSOCIATION_TITLE IN ('QSR SALES ACTUAL'))
                                                CONNECT BY PRIOR COA.COA_CDE=COA.PARENT_CDE)
              ) DDS, CHART_OF_ACCOUNT COA WHERE DDS.COA_CDE=COA.COA_CDE
              GROUP BY DDS.COA_CDE, DDS.VOUCHER_DTE
             UNION ALL
             SELECT VD.COA_CDE, 0 TARGET, 
               SUM(CASE WHEN VD.COA_CDE LIKE '500-01-01%' THEN CASE WHEN VD.QTY<0 THEN VD.QTY ELSE 0 END ELSE VD.AMNT END) SOLD, VD.VOUCHER_DTE SOLD_DTE
             FROM ( SELECT VD.COA_CDE, VM.VOUCHER_DTE, VD.AMNT, NVL(VD.QTY,0) QTY, FP_MONTH MONTH_NME 
                      FROM VOUCHER_DETAIL VD, VOUCHER_MASTER VM, VOUCHER_SUB_TYPE VST
                      WHERE VM.VOUCHER_MASTER_ID=VD.VOUCHER_MASTER_ID AND (VM.VOUCHER_DTE BETWEEN TO_DATE(FP_START_DTE,'DD-MM-YYYY') AND TO_DATE(FP_END_DTE,'DD-MM-YYYY'))
                      AND VM.VOUCHER_SUB_TYP_ID=VST.VOUCHER_SUB_TYP_ID AND VST.VOUCHER_SUB_TYP_DESC<>'CJV'
                      AND VM.SITE_ID=FP_SITE_ID AND VM.FIN_YEAR_ID=FP_FINYEAR_ID AND VM.COMPANY_ID=FP_COMPANY_ID AND VM.CANCELLED_BY IS NULL AND VM.POSTED_IND='Y'
                      AND VD.COA_CDE IN (SELECT COA.COA_CDE FROM CHART_OF_ACCOUNT COA WHERE COA.ENTRY_LEVEL_IND='Y'
                                          START WITH COA.COA_CDE IN (SELECT CAD.COA_CDE FROM COA_ASSOCIATION_DETAIL CAD, COA_ASSOCIATION CA
                                          WHERE CAD.COA_ASSOCIATION_ID=CA.COA_ASSOCIATION_ID AND CA.ASSOCIATION_TITLE IN ('QSR SALES TARGET'))
                                          CONNECT BY PRIOR COA.COA_CDE=COA.PARENT_CDE)
             ) VD GROUP BY VD.COA_CDE, VD.VOUCHER_DTE
        ) SP, CHART_OF_ACCOUNT COA WHERE SP.COA_CDE=COA.COA_CDE GROUP BY SP.COA_CDE, SP.SOLD_DTE ORDER BY SP.COA_CDE ASC, SP.SOLD_DTE ASC;
BEGIN
    FOR FL_SP IN CS_QSR_SALES_PERFORMANCE_W LOOP
      PIPE ROW (OBJECT_QSR_SALES_PERFORMANCE_W(FL_SP.COA_CDE, FL_SP.TITLE, FL_SP.TARGET, FL_SP.SOLD, FL_SP.SOLD_DTE));          
    END LOOP;
  RETURN;  
END;
/




