CREATE OR REPLACE 
FUNCTION GET_VOUCHER_NBR(FP_VOUCHER_DTE IN VARCHAR2, FP_VOUCHER_SUB_TYP IN VARCHAR2, FP_BU_ID IN NUMBER, FP_COMPANY_ID IN NUMBER)  
RETURN NUMBER IS
V_VOUCHER_NBR NUMBER;
BEGIN
  IF (TO_DATE(FP_VOUCHER_DTE,'DD-MM-YYYY') < TO_DATE('01-01-2014','DD-MM-YYYY')) THEN 
     SELECT MAX(TO_NUMBER(NVL(VM.VOUCHER_NBR,0)))+1 MAX_NBR INTO V_VOUCHER_NBR FROM VOUCHER_MASTER VM, VOUCHER_SUB_TYPE VST 
                 WHERE VM.VOUCHER_SUB_TYP_ID=VST.VOUCHER_SUB_TYP_ID AND VST.VOUCHER_SUB_TYP_DESC=FP_VOUCHER_SUB_TYP
                 AND TO_CHAR(VM.VOUCHER_DTE,'MM-yyyy')=TO_CHAR(TO_DATE(FP_VOUCHER_DTE,'dd-MM-yyyy'), 'MM-yyyy') 
                 AND VM.COMPANY_ID= FP_COMPANY_ID;
  ELSE 
     SELECT MAX(TO_NUMBER(NVL(VM.VOUCHER_NBR,0)))+1 MAX_NBR INTO V_VOUCHER_NBR FROM VOUCHER_MASTER VM, VOUCHER_SUB_TYPE VST 
                 WHERE VM.VOUCHER_SUB_TYP_ID=VST.VOUCHER_SUB_TYP_ID AND VST.VOUCHER_SUB_TYP_DESC=FP_VOUCHER_SUB_TYP
                 AND TO_CHAR(VM.VOUCHER_DTE,'MM-yyyy')=TO_CHAR(TO_DATE(FP_VOUCHER_DTE,'dd-MM-yyyy'), 'MM-yyyy') 
                 AND VM.BU_ID=FP_BU_ID
                 AND VM.COMPANY_ID= FP_COMPANY_ID;
  END IF;
  IF V_VOUCHER_NBR IS NULL THEN
    V_VOUCHER_NBR := 1;
  END IF;
  RETURN V_VOUCHER_NBR;
END; 
/

