CREATE OR REPLACE TYPE OBJ_SALES_PERFORMANCE_WEEK_NEW IS OBJECT (
  COA_CDE VARCHAR2(32), 
  TITLE VARCHAR2(128),
  GROUP_NME VARCHAR2(32),
  TARGET NUMBER, 
  SOLD NUMBER,
  SOLD_DTE VARCHAR2(8)
);
/
CREATE OR REPLACE TYPE TBL_SALES_PERFORMANCE_WEEK_NEW IS TABLE OF OBJ_SALES_PERFORMANCE_WEEK_NEW;
/
CREATE OR REPLACE
FUNCTION GET_SALES_PERFORMANCE_WEEK_NEW(FP_START_DTE IN VARCHAR2, FP_END_DTE IN VARCHAR2, FP_SITE_ID IN NUMBER, FP_FINYEAR_ID IN NUMBER, FP_COMPANY_ID IN NUMBER) 
RETURN TBL_SALES_PERFORMANCE_WEEK_NEW PIPELINED IS
CURSOR CS_SALES_PERFORMANCE_WEEK_NEW IS 
        SELECT SP.REPORT_COLUMNS_MASTER_ID, MAX(RCM.COLUMN_NME) TITLE, MAX(RCM.GROUP_NME) GROUP_NME, TO_CHAR(SP.SOLD_DTE,'MON-DD') SOLD_DTE, SUM(SP.TARGET) TARGET, 
        SUM(CASE WHEN SP.COA_CDE IS NOT NULL THEN CASE WHEN SP.COA_CDE LIKE '375-02%' THEN SP.SOLD ELSE ABS(SP.SOLD) END ELSE 0 END) SOLD 
        FROM (
             SELECT DST.REPORT_COLUMNS_MASTER_ID, NULL COA_CDE, DST.DTE SOLD_DTE, SUM(NVL(DST.TARGET,0)) TARGET, 0 SOLD
              FROM DAILY_SALE_TARGET DST WHERE (DST.DTE BETWEEN TO_DATE(FP_START_DTE,'DD-MM-YYYY') AND TO_DATE(FP_END_DTE,'DD-MM-YYYY')) 
                AND DST.SITE_ID=FP_SITE_ID AND DST.COMPANY_ID=FP_COMPANY_ID AND DST.FIN_YEAR_ID=FP_FINYEAR_ID 
              GROUP BY DST.REPORT_COLUMNS_MASTER_ID, DST.DTE 
             UNION ALL
             SELECT VD.REPORT_COLUMNS_MASTER_ID, VD.COA_CDE, VD.VOUCHER_DTE SOLD_DTE, 0 TARGET, 
             SUM(CASE WHEN VD.COA_CDE LIKE '500-01-01%' THEN CASE WHEN VD.QTY<0 THEN VD.QTY ELSE 0 END ELSE VD.AMNT END) SOLD             
             FROM ( SELECT RCD.REPORT_COLUMNS_MASTER_ID, VD.COA_CDE, VM.VOUCHER_DTE, VD.AMNT, NVL(VD.QTY,0) QTY
                    FROM VOUCHER_DETAIL VD, VOUCHER_MASTER VM, VOUCHER_SUB_TYPE VST, REPORT_COLUMNS_DETAIL RCD
                      WHERE VM.VOUCHER_MASTER_ID=VD.VOUCHER_MASTER_ID AND VM.VOUCHER_SUB_TYP_ID=VST.VOUCHER_SUB_TYP_ID 
                      AND VST.VOUCHER_SUB_TYP_DESC NOT IN ('FAL','FAG','CJV','AJV')
                      AND VM.CANCELLED_BY IS NULL AND VM.POSTED_IND='Y'
                      AND VM.SITE_ID=FP_SITE_ID AND VM.FIN_YEAR_ID=FP_FINYEAR_ID AND VM.COMPANY_ID=FP_COMPANY_ID
                      AND (VM.VOUCHER_DTE BETWEEN TO_DATE(FP_START_DTE,'DD-MM-YYYY') AND TO_DATE(FP_END_DTE,'DD-MM-YYYY'))
                      AND VD.COA_CDE=RCD.COA_CDE AND RCD.REPORT_COLUMNS_MASTER_ID IN (SELECT RCM.REPORT_COLUMNS_MASTER_ID FROM REPORT_COLUMNS_MASTER RCM 
                          WHERE RCM.REPORT_TEMPLATE_ID=9 AND RCM.COMPANY_ID=FP_COMPANY_ID)
             ) VD GROUP BY VD.REPORT_COLUMNS_MASTER_ID, VD.COA_CDE, VD.VOUCHER_DTE
        ) SP, REPORT_COLUMNS_MASTER RCM WHERE SP.REPORT_COLUMNS_MASTER_ID=RCM.REPORT_COLUMNS_MASTER_ID 
          GROUP BY SP.REPORT_COLUMNS_MASTER_ID, SP.SOLD_DTE ORDER BY SP.REPORT_COLUMNS_MASTER_ID ASC, SP.SOLD_DTE ASC;
BEGIN
    FOR FL_SP IN CS_SALES_PERFORMANCE_WEEK_NEW LOOP
      PIPE ROW (OBJ_SALES_PERFORMANCE_WEEK_NEW(FL_SP.REPORT_COLUMNS_MASTER_ID, FL_SP.TITLE, FL_SP.GROUP_NME, FL_SP.TARGET, FL_SP.SOLD, FL_SP.SOLD_DTE));          
    END LOOP;
  RETURN;  
END;
/




