CREATE OR REPLACE TYPE OBJECT_PL IS OBJECT (
  SITE_ID NUMBER,
  MONTH_NBR VARCHAR2(8),
  SEQ_NBR NUMBER,
  TITLE VARCHAR2(128),
  DISPLAY_TXT VARCHAR2(128),
  SUB_TITLE VARCHAR2(128),   
  COA_CDE VARCHAR2(32), 
  COA_TITLE VARCHAR2(128), 
  AMNT NUMBER
);
/
CREATE OR REPLACE TYPE TABLE_PL IS TABLE OF OBJECT_PL;
/
CREATE OR REPLACE
FUNCTION GET_PL(FP_MANAGEMENT_ACCOUNTS_ID IN NUMBER, FP_FROM_DTE IN VARCHAR2, FP_END_DTE IN VARCHAR2, FP_BU_ID IN NUMBER, FP_SITE_ID IN NUMBER, FP_FINYEAR_ID IN NUMBER, FP_COMPANY_ID IN NUMBER) 
RETURN TABLE_PL PIPELINED IS
CURSOR CS_PL(CP_SITE_ID IN NUMBER) IS 
  SELECT MA.*, COA.TITLE COA_TITLE FROM TABLE(GET_MANAGEMENT_ACCOUNTS(FP_MANAGEMENT_ACCOUNTS_ID, FP_FROM_DTE,FP_END_DTE,CP_SITE_ID,FP_FINYEAR_ID,FP_COMPANY_ID,'N')) MA, CHART_OF_ACCOUNT COA 
    WHERE MA.COA_CDE=COA.COA_CDE(+);
CURSOR CS_SITE IS    
  SELECT S.SITE_ID FROM SITE S, SITE_BUSINESS_UNIT SBU
    WHERE S.SITE_ID=SBU.SITE_ID AND S.COMPANY_ID=SBU.COMPANY_ID AND S.STORE_IND='Y'
      AND SBU.COMPANY_ID=FP_COMPANY_ID AND SBU.BUSINESS_UNIT_ID=FP_BU_ID AND (S.SITE_ID=FP_SITE_ID OR 0=FP_SITE_ID) -- ZERO FOR ALL SITES FOR PARTICULAR BU
    ORDER BY S.SITE_ID;    
    
BEGIN
FOR FL_S IN CS_SITE LOOP 
  FOR FL_PL IN CS_PL(FL_S.SITE_ID) LOOP   
    IF (FL_PL.TITLE='SALES' OR FL_PL.TITLE='OTHER INCOME') THEN
        PIPE ROW (OBJECT_PL(FL_S.SITE_ID, FL_PL.MONTH_NBR, FL_PL.SEQ_NBR, FL_PL.TITLE, FL_PL.DISPLAY_TXT, FL_PL.SUB_TITLE, FL_PL.COA_CDE, FL_PL.COA_TITLE, -1*(FL_PL.AMNT)));     
    ELSE  
      PIPE ROW (OBJECT_PL(FL_S.SITE_ID, FL_PL.MONTH_NBR, FL_PL.SEQ_NBR, FL_PL.TITLE, FL_PL.DISPLAY_TXT, FL_PL.SUB_TITLE, FL_PL.COA_CDE, FL_PL.COA_TITLE, FL_PL.AMNT));      
    END IF;      
  END LOOP;
END LOOP;  
END;
/