CREATE OR REPLACE 
FUNCTION GET_RECIPE_SALE_QTY(FP_COA_CDE IN VARCHAR2, FP_VOUCHER_DTE IN VARCHAR2, FP_SITE_ID IN NUMBER, FP_COMPANY_ID IN NUMBER)  
RETURN NUMBER IS
CURSOR CS_RECIPE IS SELECT SRI.COA_CDE FROM SITE_RECIPE_ITEM SRI WHERE SRI.SITE_ID=FP_SITE_ID AND SRI.COMPANY_ID=FP_COMPANY_ID;
CURSOR CS_RECIPE_ITEMS(CP_COA_CDE IN VARCHAR2) IS (  
        SELECT ROUND((NVL(VD.QTY,0) * (ALBERTA.GET_RECIPE_ITEM_QTY(VD.COA_CDE,FP_COA_CDE,VM.SITE_ID,VM.COMPANY_ID))),2) SALE_QTY
        FROM VOUCHER_DETAIL VD, VOUCHER_MASTER VM, VOUCHER_SUB_TYPE VST
        WHERE VD.VOUCHER_MASTER_ID = VM.VOUCHER_MASTER_ID AND VM.VOUCHER_SUB_TYP_ID = VST.VOUCHER_SUB_TYP_ID
        AND VM.CANCELLED_BY IS NULL AND VM.POSTED_IND='Y' AND VM.SITE_ID = FP_SITE_ID 
        AND VM.VOUCHER_DTE=TO_DATE(FP_VOUCHER_DTE,'DD-MM-YYYY')
        AND VD.COA_CDE=CP_COA_CDE AND VST.VOUCHER_TYP = 'SI' AND VM.COMPANY_ID = FP_COMPANY_ID );   
V_SALE_QTY NUMBER := 0;
BEGIN
  V_SALE_QTY := 0;
   FOR FL_R IN CS_RECIPE LOOP
    FOR FL_RI IN CS_RECIPE_ITEMS(FL_R.COA_CDE) LOOP
        V_SALE_QTY := ROUND((V_SALE_QTY + FL_RI.SALE_QTY),2);
    END LOOP;
  END LOOP;
  RETURN V_SALE_QTY;
END; 
/
 