CREATE OR REPLACE FUNCTION GET_RECIPE_ITEM_COST_PRICE (FP_VOUCHER_DTE IN VARCHAR2,FP_COA_CDE IN VARCHAR2,FP_SITE_ID IN NUMBER,FP_FIN_YEAR_ID IN NUMBER,FP_COMPANY_ID IN NUMBER) 
RETURN NUMBER 
IS
CURSOR CS_RECIPE_ITEM_COST_PRICE IS SELECT NVL(VD.BEFORE_COST_PRICE,0) BEFORE_COST_PRICE
                             FROM VOUCHER_DETAIL VD, VOUCHER_MASTER VM, VOUCHER_SUB_TYPE VST
                             WHERE VD.VOUCHER_MASTER_ID=VM.VOUCHER_MASTER_ID AND VM.VOUCHER_SUB_TYP_ID=VST.VOUCHER_SUB_TYP_ID
                             AND VM.CANCELLED_BY IS NULL AND VM.POSTED_IND='Y' AND VM.SITE_ID=FP_SITE_ID
                             AND VM.VOUCHER_DTE=TO_DATE(FP_VOUCHER_DTE,'DD-MM-YYYY') 
                             AND NVL(VD.QTY,0)<>0  AND VD.COA_CDE=FP_COA_CDE
                             AND VST.VOUCHER_SUB_TYP_DESC='SI' AND VM.COMPANY_ID=FP_COMPANY_ID  AND VM.FIN_YEAR_ID=FP_FIN_YEAR_ID;
V_ITEM_COST_PRICE NUMBER := 0;
BEGIN
  V_ITEM_COST_PRICE := 0;
  FOR FL_RECIPE_ITEM_COST_PRICE IN CS_RECIPE_ITEM_COST_PRICE LOOP
    IF (FL_RECIPE_ITEM_COST_PRICE.BEFORE_COST_PRICE > 0) THEN
      V_ITEM_COST_PRICE := FL_RECIPE_ITEM_COST_PRICE.BEFORE_COST_PRICE;
    END IF;
  END LOOP;
  RETURN V_ITEM_COST_PRICE;
END; 
/