CREATE OR REPLACE TYPE OBJECT_QSR_SALES_PERFORMANCE IS OBJECT (
  COA_CDE VARCHAR2(32), 
  TITLE VARCHAR2(128),
  TARGET NUMBER,
  T_W1 NUMBER, 
  T_W2 NUMBER, 
  T_W3 NUMBER, 
  T_W4 NUMBER, 
  T_W5 NUMBER,
  S_W1 NUMBER, 
  S_W2 NUMBER, 
  S_W3 NUMBER, 
  S_W4 NUMBER, 
  S_W5 NUMBER  
);
/
CREATE OR REPLACE TYPE TABLE_QSR_SALES_PERFORMANCE IS TABLE OF OBJECT_QSR_SALES_PERFORMANCE;
/
CREATE OR REPLACE
FUNCTION GET_QSR_SALES_PERFORMANCE(FP_MONTH IN VARCHAR2, FP_SITE_ID IN NUMBER, FP_FINYEAR_ID IN NUMBER, FP_COMPANY_ID IN NUMBER) 
RETURN TABLE_QSR_SALES_PERFORMANCE PIPELINED IS
CURSOR CS_QSR_SALES_PERFORMANCE IS 
        SELECT SP.COA_CDE, MAX(COA.TITLE) TITLE, SUM(SP.TARGET) TARGET, ABS(SUM(SP.T_W1)) T_W1, ABS(SUM(SP.T_W2)) T_W2, ABS(SUM(SP.T_W3)) T_W3, 
        ABS(SUM(SP.T_W4)) T_W4, ABS(SUM(SP.T_W5)) T_W5, ABS(SUM(SP.S_W1)) S_W1, ABS(SUM(SP.S_W2)) S_W2, ABS(SUM(SP.S_W3)) S_W3, 
        ABS(SUM(SP.S_W4)) S_W4, ABS(SUM(SP.S_W5)) S_W5 FROM (
             SELECT COA.COA_CDE, NVL(ST.TARGET,0) TARGET, NVL(ST.T_W1,0) T_W1, NVL(ST.T_W2,0) T_W2, NVL(ST.T_W3,0) T_W3, 
             NVL(ST.T_W4,0) T_W4, NVL(ST.T_W5,0) T_W5, 0 S_W1, 0 S_W2, 0 S_W3, 0 S_W4, 0 S_W5 FROM (
                  SELECT QTD.COA_CDE, SUM(NVL(TARGET,0)) TARGET,
                  SUM(CASE WHEN QTD.WEEK='W1' THEN NVL(TARGET,0) ELSE 0 END) T_W1, 
                  SUM(CASE WHEN QTD.WEEK='W2' THEN NVL(TARGET,0) ELSE 0 END) T_W2, 
                  SUM(CASE WHEN QTD.WEEK='W3' THEN NVL(TARGET,0) ELSE 0 END) T_W3, 
                  SUM(CASE WHEN QTD.WEEK='W4' THEN NVL(TARGET,0) ELSE 0 END) T_W4, 
                  SUM(CASE WHEN QTD.WEEK='W5' THEN NVL(TARGET,0) ELSE 0 END) T_W5
                  FROM QSR_TARGET_MASTER QTM,QSR_TARGET_DETAIL QTD
                   WHERE QTM.QSR_TARGET_MASTER_ID=QTD.QSR_TARGET_MASTER_ID
                   AND QTM.FIN_YEAR_ID=FP_FINYEAR_ID AND QTM.SITE_ID=FP_SITE_ID
                   AND QTM.MONTH_NME=FP_MONTH AND QTM.COMPANY_ID=FP_COMPANY_ID
                  GROUP BY QTD.COA_CDE                  
             ) ST, CHART_OF_ACCOUNT COA 
             WHERE COA.COA_CDE=ST.COA_CDE(+) AND COA.COMPANY_ID=FP_COMPANY_ID 
             AND COA.COA_CDE IN (SELECT COA.COA_CDE FROM CHART_OF_ACCOUNT COA WHERE COA.ENTRY_LEVEL_IND='Y'
                                   START WITH COA.COA_CDE IN (SELECT CAD.COA_CDE FROM COA_ASSOCIATION_DETAIL CAD, COA_ASSOCIATION CA
                                   WHERE CAD.COA_ASSOCIATION_ID=CA.COA_ASSOCIATION_ID AND CA.ASSOCIATION_TITLE IN ('QSR SALES TARGET', 'QSR SALES ACTUAL'))
                                   CONNECT BY PRIOR COA.COA_CDE=COA.PARENT_CDE) 
             UNION ALL
             SELECT DDS.COA_CDE, 0 TARGET, 0 T_W1, 0 T_W2, 0 T_W3, 0 T_W4, 0 T_W5, 
               SUM(CASE WHEN (MW.WEEK=1 AND (DDS.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DDS.SAL_QTY ELSE 0 END) S_W1,
               SUM(CASE WHEN (MW.WEEK=2 AND (DDS.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DDS.SAL_QTY ELSE 0 END) S_W2,
               SUM(CASE WHEN (MW.WEEK=3 AND (DDS.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DDS.SAL_QTY ELSE 0 END) S_W3,
               SUM(CASE WHEN (MW.WEEK=4 AND (DDS.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DDS.SAL_QTY ELSE 0 END) S_W4,
               SUM(CASE WHEN (MW.WEEK=5 AND (DDS.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN  DDS.SAL_QTY ELSE 0 END) S_W5
              FROM ( SELECT DDS.COA_CDE, DDS.VOUCHER_DTE, NVL(DDS.SAL_QTY,0) SAL_QTY, DDS.MONTH_NME FROM DEPT_DAILY_SALE DDS
                      WHERE DDS.MONTH_NME=FP_MONTH AND DDS.SITE_ID=FP_SITE_ID  AND DDS.FIN_YEAR_ID=FP_FINYEAR_ID AND DDS.COMPANY_ID=FP_COMPANY_ID
                        AND DDS.COA_CDE IN (SELECT COA.COA_CDE FROM CHART_OF_ACCOUNT COA WHERE COA.ENTRY_LEVEL_IND='Y'
                                            START WITH COA.COA_CDE IN (SELECT CAD.COA_CDE FROM COA_ASSOCIATION_DETAIL CAD, COA_ASSOCIATION CA
                                              WHERE CAD.COA_ASSOCIATION_ID=CA.COA_ASSOCIATION_ID AND CA.ASSOCIATION_TITLE IN ('QSR SALES ACTUAL'))
                                                CONNECT BY PRIOR COA.COA_CDE=COA.PARENT_CDE)
              ) DDS, MONTH_WEEKS MW WHERE DDS.MONTH_NME=MW.MONTH_NME AND MW.WEEK_FOR='QSR' GROUP BY DDS.COA_CDE
             UNION ALL
             SELECT VD.COA_CDE, 0 TARGET, 0 T_W1, 0 T_W2, 0 T_W3, 0 T_W4, 0 T_W5, 
               SUM(CASE WHEN (MW.WEEK=1 AND (VD.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN VD.AMNT ELSE 0 END) S_W1,
               SUM(CASE WHEN (MW.WEEK=2 AND (VD.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN VD.AMNT ELSE 0 END) S_W2,
               SUM(CASE WHEN (MW.WEEK=3 AND (VD.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN VD.AMNT ELSE 0 END) S_W3,
               SUM(CASE WHEN (MW.WEEK=4 AND (VD.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN VD.AMNT ELSE 0 END) S_W4,
               SUM(CASE WHEN (MW.WEEK=5 AND (VD.VOUCHER_DTE BETWEEN MW.START_DATE AND MW.END_DATE)) THEN VD.AMNT ELSE 0 END) S_W5
             FROM ( SELECT VD.COA_CDE, VM.VOUCHER_DTE, VD.AMNT, NVL(VD.QTY,0) QTY, FP_MONTH MONTH_NME 
                      FROM VOUCHER_DETAIL VD, VOUCHER_MASTER VM, VOUCHER_SUB_TYPE VST
                      WHERE VM.VOUCHER_MASTER_ID=VD.VOUCHER_MASTER_ID AND TO_CHAR(VM.VOUCHER_DTE,'MON-YYYY')=UPPER(FP_MONTH)
                      AND VM.VOUCHER_SUB_TYP_ID=VST.VOUCHER_SUB_TYP_ID AND VST.VOUCHER_SUB_TYP_DESC<>'CJV'
                      AND VM.SITE_ID=FP_SITE_ID  AND VM.FIN_YEAR_ID=FP_FINYEAR_ID  AND VM.COMPANY_ID=FP_COMPANY_ID  AND VM.CANCELLED_BY IS NULL AND VM.POSTED_IND='Y'
                      AND VD.COA_CDE IN (SELECT COA.COA_CDE FROM CHART_OF_ACCOUNT COA WHERE COA.ENTRY_LEVEL_IND='Y'
                                          START WITH COA.COA_CDE IN (SELECT CAD.COA_CDE FROM COA_ASSOCIATION_DETAIL CAD, COA_ASSOCIATION CA
                                          WHERE CAD.COA_ASSOCIATION_ID=CA.COA_ASSOCIATION_ID AND CA.ASSOCIATION_TITLE IN ('QSR SALES TARGET'))
                                          CONNECT BY PRIOR COA.COA_CDE=COA.PARENT_CDE)
             ) VD, MONTH_WEEKS MW WHERE VD.MONTH_NME=MW.MONTH_NME AND MW.WEEK_FOR='QSR' GROUP BY VD.COA_CDE
        ) SP, CHART_OF_ACCOUNT COA WHERE SP.COA_CDE=COA.COA_CDE GROUP BY SP.COA_CDE ORDER BY SP.COA_CDE ASC;
BEGIN
    FOR FL_SP IN CS_QSR_SALES_PERFORMANCE LOOP
      PIPE ROW (OBJECT_QSR_SALES_PERFORMANCE(FL_SP.COA_CDE, FL_SP.TITLE, FL_SP.TARGET, FL_SP.T_W1, FL_SP.T_W2, FL_SP.T_W3, FL_SP.T_W4, FL_SP.T_W5,
              FL_SP.S_W1, FL_SP.S_W2, FL_SP.S_W3, FL_SP.S_W4, FL_SP.S_W5));          
    END LOOP;
  RETURN;  
END;
/




