CREATE OR REPLACE PROCEDURE UPDAET_EMP_SCHEDULE_DEPT
AS
CURSOR CUR_ES IS SELECT ES.EMPLOYEE_SCHEDULE_ID, ES.EMP_ID, TO_CHAR(ES.DTE,'DD-MM-YYYY') DTE FROM EMPLOYEE_SCHEDULE ES ORDER BY ES.EMPLOYEE_SCHEDULE_ID;
CURSOR CUR_ED(CP_EMP_ID IN NUMBER, CP_DTE IN VARCHAR2) IS 
  SELECT MAX(ED.DEPT_ID) DEPT_ID FROM EMPLOYEE_DEPARTMENT ED
    WHERE ED.EMP_ID=CP_EMP_ID
      AND TO_DATE(CP_DTE,'DD-MM-YYYY') BETWEEN TO_DATE(TO_CHAR(ED.START_DTE,'DD-MM-YYYY'),'DD-MM-YYYY') AND TO_DATE(TO_CHAR(NVL(ED.END_DTE, SYSDATE),'DD-MM-YYYY'),'DD-MM-YYYY')
    ORDER BY ED.START_DTE;                          
BEGIN
  FOR FL_ES IN CUR_ES LOOP
    FOR FL_ED IN CUR_ED(FL_ES.EMP_ID, FL_ES.DTE) LOOP
      UPDATE COMMUNICATION.EMPLOYEE_SCHEDULE SET DEPT_ID=FL_ED.DEPT_ID WHERE EMPLOYEE_SCHEDULE_ID=FL_ES.EMPLOYEE_SCHEDULE_ID;
    END LOOP;    
  END LOOP;  
  COMMIT;
END;  